spring:
  datasource:
    username: sa
    password: ${PWD}
    url: jdbc:h2:mem:goods_db
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.H2Dialect

  liquibase:
    change-log: classpath:db/migration/changelog.xml
    enabled: true

  h2:
    console:
      enabled: true #http://localhost:8080/my-app/h2-console/


